In [4]:
import numpy as np
import pandas as pd
import os
from PIL import Image

def label_array(row):
    return (np.asarray(Image.open(os.path.join('images',row['image-name'])))/255).astype('float32')

data = pd.read_csv("data.csv")
data['image-array'] = data.apply(lambda row: label_array(row), axis=1)
data['label'] -= 1

In [2]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

train_set, test_set = train_test_split(data, test_size=0.2, random_state=42)

X_train = np.stack(train_set['image-array'].values)
y_train = np.stack(train_set['label'].values)


n_clf = KNeighborsClassifier(1)
n_clf.fit(X_train,y_train)


X_test = np.stack(test_set['image-array'].values)
y_test = np.stack(test_set['label'].values)

print(n_clf.score(X_test,y_test))
print(cross_val_score(n_clf, X_train, y_train, cv=3, scoring="accuracy"))



0.4603174603174603
[0.44047619 0.44642857 0.48502994]


In [7]:
X_test = np.stack(test_set['image-array'].values)
y_test = np.stack(test_set['label'].values)

n_clf.score(X_test,y_test)

0.3888888888888889

In [9]:
test_set

image-name  label    label-name  \
494    495.jpg     21  characters-3   
244    245.jpg     34  honors-white   
551    552.jpg     29  honors-south   
213    214.jpg     21  characters-3   
532    533.jpg     21  characters-3   
..         ...    ...           ...   
349    350.jpg      8        dots-8   
320    321.jpg     27  characters-9   
218    219.jpg     33  honors-green   
408    409.jpg     12      bamboo-3   
438    439.jpg      4        dots-4   

                                           image-array  
494  [158, 137, 118, 167, 146, 127, 185, 164, 145, ...  
244  [230, 230, 230, 229, 229, 229, 228, 228, 228, ...  
551  [238, 225, 209, 232, 219, 203, 222, 209, 193, ...  
213  [143, 167, 201, 143, 167, 201, 141, 167, 202, ...  
532  [232, 225, 206, 218, 210, 191, 161, 153, 134, ...  
..                                                 ...  
349  [250, 246, 245, 251, 247, 246, 251, 247, 246, ...  
320  [119, 123, 100, 124, 128, 105, 135, 139, 116, ...  
218  [196, 188, 107, 196, 188, 105, 196, 190, 102, ...  
408  [157, 141, 107, 159, 143, 109, 161, 145, 111, ...  
438  [64, 59, 53, 62, 57, 51, 60, 55, 49, 59, 56, 5...  

[126 rows x 4 columns]

In [16]:
print(n_clf.predict([np.asarray(Image.open(os.path.join('images','552.jpg'))).flatten()]))

[30]


In [21]:
0.4603174603174603

0.4603174603174603

In [22]:
from sklearn.ensemble import RandomForestClassifier
forest_clf = RandomForestClassifier()
forest_clf.fit(X_train,y_train)
print(cross_val_score(forest_clf, X_train, y_train, cv=3, scoring="accuracy"))




[0.51190476 0.35714286 0.48502994]


In [32]:
def label_array_offset(row):
    return np.asarray(Image.open(os.path.join('offsetImages',row['image-name']))).flatten()

data_offset = pd.read_csv("data.csv")
data_offset['image-array'] = data.apply(lambda row: label_array_offset(row), axis=1)

data1 = pd.concat([data,data_offset],ignore_index = True)

In [28]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   image-name   1258 non-null   object
 1   label        1258 non-null   int64 
 2   label-name   1258 non-null   object
 3   image-array  1258 non-null   object
dtypes: int64(1), object(3)
memory usage: 39.4+ KB


In [33]:


train_set1, test_set1 = train_test_split(data1, test_size=0.2, random_state=42)

X_train1 = np.stack(train_set['image-array'].values)
y_train1 = np.stack(train_set['label'].values)

forest_clf1 = RandomForestClassifier()
forest_clf1.fit(X_train1,y_train1)
print(cross_val_score(forest_clf1, X_train1, y_train1, cv=3, scoring="accuracy"))

[0.51785714 0.44642857 0.47305389]


In [36]:
n_clf1 = KNeighborsClassifier(3)
n_clf1.fit(X_train1,y_train1)
print(cross_val_score(n_clf1, X_train1, y_train1, cv=3, scoring="accuracy"))

[0.41666667 0.38690476 0.43712575]


In [5]:
from PIL.ImageFilter import (
   BLUR, CONTOUR, DETAIL, EDGE_ENHANCE, EDGE_ENHANCE_MORE,
   EMBOSS, FIND_EDGES, SMOOTH, SMOOTH_MORE, SHARPEN
)

def label_array(row):
    return np.asarray(Image.open(os.path.join('images',row['image-name'])).filter(EDGE_ENHANCE)).flatten()

data = pd.read_csv("data.csv")
data['image-array'] = data.apply(lambda row: label_array(row), axis=1)

In [6]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

train_set, test_set = train_test_split(data, test_size=0.2, random_state=42)

#X = np.stack(train_set['image'].values)
#y = np.stack(train_set['label'].values)
X_train = np.stack(train_set['image-array'].values)
y_train = np.stack(train_set['label'].values)


n_clf = KNeighborsClassifier(1)
n_clf.fit(X_train,y_train)


X_test = np.stack(test_set['image-array'].values)
y_test = np.stack(test_set['label'].values)

print(n_clf.score(X_test,y_test))
print(cross_val_score(n_clf, X_train, y_train, cv=3, scoring="accuracy"))

0.42857142857142855
[0.41071429 0.41071429 0.43113772]


In [4]:
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

train_set, test_set = train_test_split(data, test_size=0.2, random_state=42)

X_train = np.stack(train_set['image-array'].values)
y_train = np.stack(train_set['label'].values)


per_clf = Perceptron()
per_clf.fit(X_train, y_train)

print(cross_val_score(per_clf, X_train, y_train, cv=3, scoring="accuracy"))

[0.51190476 0.57738095 0.47305389]


In [2]:
import tensorflow as tf
from tensorflow import keras

In [3]:
from sklearn.model_selection import train_test_split
model = keras.models.Sequential()

train_set, test_set = train_test_split(data, test_size=0.2, random_state=42)

X_train = np.stack(train_set['image-array'].values)
y_train = np.stack(train_set['label'].values)

model.add(keras.layers.Flatten(input_shape=[320, 240, 3]))
#model.add(keras.layers.Dense(30, activation="relu"))
#model.add(keras.layers.Dense(10, activation="relu"))
model.add(keras.layers.Dense(43, activation="softmax"))
optimizer = keras.optimizers.SGD()
model.compile(loss="sparse_categorical_crossentropy",
    optimizer=optimizer,
    metrics=["accuracy"])



history = model.fit(X_train, y_train, epochs=50,validation_split = 0.1)

NameError: name 'data' is not defined

In [11]:
np.shape(data['image-array'][0])

(320, 240, 3)

In [6]:
label = pd.DataFrame([data['label'],data['label-name']]).T.drop_duplicates().set_index('label').to_dict(orient='dict')['label-name']
label = {v: k for k, v in label.items()}

label

{'bonus-winter': 37,
 'characters-8': 25,
 'dots-9': 8,
 'bonus-summer': 35,
 'honors-east': 27,
 'bonus-autumn': 36,
 'characters-6': 23,
 'bamboo-7': 15,
 'honors-north': 30,
 'honors-west': 29,
 'characters-2': 19,
 'characters-5': 22,
 'dots-3': 2,
 'characters-4': 21,
 'dots-2': 1,
 'honors-south': 28,
 'characters-7': 24,
 'dots-7': 6,
 'dots-6': 5,
 'honors-green': 32,
 'bamboo-3': 11,
 'bamboo-1': 9,
 'honors-red': 31,
 'bonus-chrysanthemum': 40,
 'honors-white': 33,
 'bonus-plum': 38,
 'characters-9': 26,
 'characters-1': 18,
 'characters-3': 20,
 'dots-5': 4,
 'bamboo-8': 16,
 'bamboo-6': 14,
 'dots-4': 3,
 'bamboo-2': 10,
 'bamboo-4': 12,
 'dots-8': 7,
 'bamboo-9': 17,
 'dots-1': 0,
 'bonus-bamboo': 41,
 'bamboo-5': 13,
 'bonus-spring': 34,
 'bonus-orchid': 39}

In [57]:
X_test = np.stack(test_set['image-array'].values)
y_test = np.stack(test_set['label'].values)

model.evaluate(X_test, y_test)

4/4 [==============================] - 0s 11ms/step - loss: 14.1388 - accuracy: 0.6905


[14.138776779174805, 0.6904761791229248]

In [62]:
from PIL import Image, ImageChops

In [75]:
im = (np.asarray(Image.open('37.jpg'))/255).astype('float32')
np.shape(im)
model.predict(im)

ValueError: in user code:

    C:\Users\Kirill\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:1462 predict_function  *
        return step_function(self, iterator)
    C:\Users\Kirill\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:1452 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Kirill\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Kirill\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Kirill\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Kirill\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:1445 run_step  **
        outputs = model.predict_step(data)
    C:\Users\Kirill\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:1418 predict_step
        return self(x, training=False)
    C:\Users\Kirill\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\base_layer.py:985 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    C:\Users\Kirill\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\sequential.py:372 call
        return super(Sequential, self).call(inputs, training=training, mask=mask)
    C:\Users\Kirill\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\functional.py:386 call
        inputs, training=training, mask=mask)
    C:\Users\Kirill\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\functional.py:508 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    C:\Users\Kirill\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\base_layer.py:976 __call__
        self.name)
    C:\Users\Kirill\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\input_spec.py:216 assert_input_compatibility
        ' but received input with shape ' + str(shape))

    ValueError: Input 0 of layer dense_7 is incompatible with the layer: expected axis -1 of input shape to have value 230400 but received input with shape [32, 720]
