In [22]:
import numpy as np
x = np.arange(12,dtype = "uint16").reshape(3,4)
print("Printing array")
print(x)
print("Printing attributes")
print('Array shape is: ',end="")
print(x.shape)
print('Array dimensions are ',end ="")
print(x.ndim)
print('Length of each element of array in bytes is ',end='')
print(x.itemsize)


Printing array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Printing attributes
Array shape is: (3, 4)
Array dimensions are 2
Length of each element of array in bytes is 2


In [25]:
x = np.linspace(100,190,10,dtype="int16").reshape(5,2)
print(x)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [29]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray)
print(sampleArray[:,1])

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[22 55 88]


In [32]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray)
print(sampleArray[0::2,1::2])

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[ 6 12]
 [30 36]
 [54 60]]


In [35]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
print(arrayOne)
print(arrayTwo)
print((arrayOne+arrayTwo)**2)

[[ 5  6  9]
 [21 18 27]]
[[15 33 24]
 [ 4  7  1]]
[[ 400 1521 1089]
 [ 625  625  784]]


In [41]:
x = np.arange(10,34).reshape(8,3)
x1,x2,x3,x4 = np.vsplit(x,[2,4,6])
print(x)
print(x1)
print(x2)
print(x3)
print(x4)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]
[[10 11 12]
 [13 14 15]]
[[16 17 18]
 [19 20 21]]
[[22 23 24]
 [25 26 27]]
[[28 29 30]
 [31 32 33]]


In [50]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
args = np.argsort(sampleArray[1,:])
print(sampleArray[:,args])
args = np.argsort(sampleArray[:,1])
print(sampleArray[args,:])

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[73 43 34]
 [12 22 82]
 [66 94 53]]
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [54]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(np.min(sampleArray,axis=1))
print(np.max(sampleArray,axis=0))

[34 12 53]
[82 94 73]


In [60]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

newColumn = np.array([[10,10,10]])
print(sampleArray)
print(sampleArray[:,[0,2]])
sampleArray[:,1] = newColumn
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 73]
 [82 12]
 [53 66]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]
