In [3]:
import numpy as np
print(np.__version__)

1.19.2


In [4]:
lst = [1.23, 132.1, 12.5, 38.263]
x = np.array(lst)
print(x)

[  1.23  132.1    12.5    38.263]


In [6]:
x = np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [8]:
x = np.zeros(10)
x[6] = 11
print(x)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [11]:
x = np.arange(12,39)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [17]:
x = x[::-1]
print(x)

[38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15
 14 13 12]


In [20]:
x = np.array([1,2,3,4])
print(x)
x = x.astype('float64')
print(x)

[1 2 3 4]
[1. 2. 3. 4.]


In [25]:
n = 20
x = np.zeros(n**2).reshape(n,n)
x[0,:] = 1
x[-1,:] = 1
x[:,0] = 1
x[:,-1] = 1
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [26]:
n = 20
x = np.ones(n**2).reshape(n,n)
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [31]:
n = 5
x = np.ones(n**2).reshape(n,n)
x = np.pad(x,1)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [38]:
x = np.zeros(64,dtype = 'int32').reshape(8,8)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [44]:
tp = ([1,2,3],[2,3,4])
x = np.array(tp)
print(x)
lst = [1,2,3]
x = np.array(lst)
print(x)

[[1 2 3]
 [2 3 4]]
[1 2 3]


In [46]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x = np.concatenate([x,y])
print(x)

[1 2 3 4 5 6]


In [50]:
x = np.empty(9).reshape(3,3)
print(x)
x = np.full(9,5).reshape(3,3)
print(x)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.14617663e-321]
 [7.56593016e-307 1.11261027e-306 4.84184333e-322]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [56]:
x = np.array([0, 12, 45.21 ,34, 99.91])
x = x *(9/5) + 32

In [57]:
x = np.array([[ 1.00000000+0.j, 0.70710678+0.70710678j]])
print(x)
print(x.real)
print(x.imag)

[[1.        +0.j         0.70710678+0.70710678j]]
[[1.         0.70710678]]
[[0.         0.70710678]]


In [62]:
x = np.arange(3,14)
print(x)
print("Size of the array: ",end = "")
print(x.size)
print("Length of one array element in bytes: ",end = "")
print(x.itemsize)
print("Total bytes consumed by the elements of the array: ",end = "")
print(x.nbytes)

[ 3  4  5  6  7  8  9 10 11 12 13]
Size of the array: 11
Length of one array element in bytes: 4
Total bytes consumed by the elements of the array: 44


In [68]:
x = np.array([1,2,45,7,32])
y = np.array([3,7,2])
mask = np.in1d(x,y)
print(mask)

[False  True False  True False]


In [69]:
x = np.array([1,2,45,7,32])
y = np.array([3,7,2])
print(np.intersect1d(x,y))

[2 7]


In [71]:
x = np.array([1,2,3,1,3])
print(np.unique(x))

[1 2 3]


In [74]:
x = np.array([1,2,45,7,32,32])
y = np.array([3,7,2])
print(np.setdiff1d(x, y, assume_unique=False))

[ 1 32 45]


In [78]:
x = np.array([1,2,45,7,32])
y = np.array([3,7,2])
print(np.concatenate([np.setdiff1d(x,y),np.setdiff1d(y,x)]))

[ 1 32 45  3]


In [79]:
x = np.array([1,2,45,7,32])
y = np.array([3,7,2])
print(np.union1d(x,y))

[ 1  2  3  7 32 45]


In [87]:
x = np.array([1,1,1],dtype=bool)
print(x.all())

True


In [88]:
x = np.array([1,1,1],dtype=bool)
print(x.any())

True


In [89]:
x = np.arange(5)
print(x)
print(np.concatenate([x,x]))
print(np.concatenate([x,x,x]))

[0 1 2 3 4]
[0 1 2 3 4 0 1 2 3 4]
[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


In [90]:
x = np.arange(5)
print(x)
print(np.tile(x,2))
print(np.tile(x,3))

[0 1 2 3 4]
[0 1 2 3 4 0 1 2 3 4]
[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


In [92]:
x = np.arange(5)
y = x.repeat(2)
print(y)

[0 0 1 1 2 2 3 3 4 4]


In [96]:
a = np.array([1,3,6,2,5,21,17,62,0,33,4])
print(a.argmax())
print(a.argmin())

7
8
